### ISSUE TITLE
DOES NOT WORK WITH MY CSV!!!111!!1!11

### ISSUE THREAD

**Issue by jodersky** [Inpher/anycsv#1]
This library doesn't work with my CSV file (in the attachement). 
I'm able to run the librarie's included test file, but it fails when I run it on my CSV file. :disappointed:

I get the following error:
```
anycsv.exceptions.NoDelimiterException: No delimiter detected
```

**Comment by alpetric** [comment]
there is no attachment ❓ ❗️

**Comment by jodersky** [comment]
Oh, I forgot to include it. Here it is.
[data.zip](https://github.com/Inpher/anycsv/files/3010476/data.zip)
